apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - middleware-https.yml
  - postgres-svc.yml
  - redis-deploy.yml
  - redis-svc.yml
  - deploy.yml
  - svc.yml
  - ingress.yml

commonLabels:
  app.kubernetes.io/part-of: truthmetal
  environment: production
