# ExternalSecret syncs rbx-comms-secrets from rbx-ia-br namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rbx-comms-secrets
  namespace: rbx-comms
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: kubernetes-store
    kind: SecretStore
  target:
    name: rbx-comms-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: rbx-comms-secrets
        property: DATABASE_URL
