apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rbx-comms

resources:
  - namespace.yml
  - rbac-external-secrets.yml
  - secretstore.yml
  - externalsecret.yml
  - externalsecret-contact.yml
  - middleware.yml
  - certificate.yml
  - ingressroute.yml
  - postgres-svc.yml
  - deploy.yml
  - svc.yml
