apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kulinaryos
resources:
  - middleware.yml
  - certificate.yml
  - secretstore.yml
  - externalsecret-s3.yml
  - institutional.yml
  - ingressroute.yml
labels:
  - pairs:
      app.kubernetes.io/part-of: kulinaryos
      environment: production
    includeSelectors: false
