apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kulinaryos-v1
resources:
  - namespace.yml
  - middleware.yml
  - certificate.yml
  - origin.yml
  - ingressroute.yml
labels:
  - pairs:
      app.kubernetes.io/part-of: kulinaryos
      environment: production
    includeSelectors: false
