apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thalamus
resources:
  - maintenance-cronjob.yml
  - namespace.yml
  - policy-config.yml
  - postgres-svc.yml
  - deploy.yml
  - svc.yml
  - network-policy.yml
images:
  - name: ghcr.io/rbxrobotica/thalamus-core
    newTag: sha-817e753
