# ClusterIssuer: Let's Encrypt Production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: letsencrypt-prod
    app.kubernetes.io/part-of: rbx-infra
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@rbx.ia.br
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: robson-gateway
                namespace: robson
                kind: Gateway
