# Kustomization for Robson Production
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace
  - namespace.yml
  # Robson trading app
  - middleware-https.yml
  - frontend-deploy.yml
  - frontend-svc.yml
  - frontend-ingress.yml
  - backend-deploy.yml
  - backend-svc.yml
  - backend-ingress.yml
  - redis-deploy.yml
  - redis-svc.yml
  - paradedb-svc.yml
  - cronjobs.yml

labels:
  - pairs:
      app.kubernetes.io/part-of: robson
      environment: production
    includeSelectors: false


