# ServiceAccount and RBAC for External Secrets to read secrets from rbx-ia-br
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-reader
  namespace: rbx-maestro

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-maestro-secret
  namespace: rbx-ia-br
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rbx-maestro-db", "corbetti-runner-key"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-reader-maestro
  namespace: rbx-ia-br
subjects:
  - kind: ServiceAccount
    name: external-secrets-reader
    namespace: rbx-maestro
roleRef:
  kind: Role
  name: read-maestro-secret
  apiGroup: rbac.authorization.k8s.io
