# ExternalSecret syncs rbx-maestro-db from rbx-ia-br namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rbx-maestro-db
  namespace: rbx-maestro
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: kubernetes-store
    kind: SecretStore
  target:
    name: rbx-maestro-db
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: rbx-maestro-db
        property: url
