apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rbx-ledger

resources:
  - namespace.yml
  - rbac-external-secrets.yml
  - secretstore.yml
  - rbx-ledger-secret.yml
  - configmap.yml
  - backend-deploy.yml
  - backend-svc.yml
  - frontend-deploy.yml
  - frontend-svc.yml
  - ingress.yml
