apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - rbac-external-secrets.yml
  - secretstore.yml
  - rbx-commerce-sandbox-secret.yml
  - paradedb-svc.yml
  - rbx-commerce-sandbox-ingress.yml
  - rbx-commerce-sandbox-deploy.yml
  - rbx-commerce-sandbox-svc.yml

images:
  - name: ghcr.io/rbxrobotica/rbx-commerce
    newTag: sha-9a8d06c62d6828b4a4ef342db467cf6306cfae4f

labels:
  - pairs:
      app.kubernetes.io/part-of: rbx-commerce
      environment: sandbox
    includeSelectors: false
