apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - rbac-external-secrets.yml
  - secretstore.yml
  - rbx-commerce-sandbox-secret.yml
  - paradedb-svc.yml
  - rbx-commerce-sandbox-ingress.yml
  - rbx-commerce-sandbox-deploy.yml
  - rbx-commerce-sandbox-svc.yml
images:
  - name: ghcr.io/rbxrobotica/rbx-commerce
    newTag: sha-d9fb5da27d42bb6aabb1f7eae1c104ec5e51b312
labels:
  - pairs:
      app.kubernetes.io/part-of: rbx-commerce
      environment: sandbox
    includeSelectors: false
