apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rbx-data-token
  namespace: rbx-data
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: kubernetes-store
    kind: SecretStore
  target:
    name: rbx-data-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: rbx-data-token
        property: token
