# Namespace: argos-radar
apiVersion: v1
kind: Namespace
metadata:
  name: argos-radar
  labels:
    app.kubernetes.io/part-of: argos-radar
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
