apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kulinaryos
resources:
  - namespace.yml
  - middleware.yml
  - certificate.yml
  - ingressroute.yml
  - deploy.yml
  - svc.yml
labels:
  - pairs:
      app.kubernetes.io/part-of: kulinaryos
      environment: production
    includeSelectors: false
images:
  # Subsequent tags are promoted by the KulinaryOS CI via RBX_INFRA_PAT.
  - name: ghcr.io/rbxrobotica/kulinaryos-web
    newTag: sha-ed418cf58a1f8299a7cdf3a93f29e10b6ae0619c
