# Kustomization for lda-prod (leandrodamasio.rbx.ia.br)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - middleware-https.yml
  - deploy.yml
  - svc.yml
  - ingress.yml

commonLabels:
  app.kubernetes.io/part-of: lda-prod
  environment: production

images:
  - name: docker.io/ldamasio/lda-prod
    newTag: sha-692c43a
