# Namespace: lda-prod
apiVersion: v1
kind: Namespace
metadata:
  name: lda-prod
  labels:
    app.kubernetes.io/part-of: lda-prod
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
