apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - secretstore.yml
  - externalsecret.yml
  - serviceaccount.yml
  - rbac.yml
  - configmap.yml
  - cronjob.yml

images:
  - name: ghcr.io/rbxrobotica/rbx-market-briefing
    newTag: sha-e05a6a0
    digest: sha256:b17bf8f6bd45abfe4b227e25abc79b6de35fb9145806d6e599af60b110209ec2
