apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - secretstore.yml
  - externalsecret.yml
  - serviceaccount.yml
  - rbac.yml
  - configmap.yml
  - cronjob.yml

images:
  - name: ghcr.io/rbxrobotica/rbx-market-briefing
    newTag: sha-6a22032
    digest: sha256:ff4be67452e5ac9b553eada3eec98fe22a8f15bba6ffa16008944ee71e39a126
