apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rbx-applications
  namespace: argocd
  labels:
    app.kubernetes.io/name: rbx-applications
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: rbx-infra
spec:
  description: Product application deployments
  sourceRepos:
    - https://github.com/rbxrobotica/rbx-infra
  destinations:
    - namespace: robson
      server: https://kubernetes.default.svc
    - namespace: robson-v2
      server: https://kubernetes.default.svc
    - namespace: lda-prod
      server: https://kubernetes.default.svc
    - namespace: rbx-ia-br
      server: https://kubernetes.default.svc
    - namespace: rbxsystems-ch
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: strategos
      server: https://kubernetes.default.svc
    - namespace: thalamus
      server: https://kubernetes.default.svc
    - namespace: websites
      server: https://kubernetes.default.svc
    - namespace: truthmetal
      server: https://kubernetes.default.svc
    - namespace: argos-radar
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: gateway.networking.k8s.io
      kind: Gateway
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: networking.k8s.io
      kind: IngressClass
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: developer
      description: Developers with namespace-scoped access
      policies:
        - p, proj:rbx-applications:developer, applications, get,
          rbx-applications/*, allow
        - p, proj:rbx-applications:developer, applications, sync,
          rbx-applications/*, allow
        - p, proj:rbx-applications:developer, exec, *, rbx-applications/*, allow
        - p, proj:rbx-applications:developer, logs, get, rbx-applications/*,
          allow
      groups:
        - rbx:developers
