# Kustomization for rbxsystems-ch (rbxsystems.ch)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - middleware-https.yml
  - deploy.yml
  - svc.yml
  - ingress.yml
  - rbac-external-secrets.yml
  - secretstore-k8s.yml
  - externalsecret-s3.yml

commonLabels:
  app.kubernetes.io/part-of: rbxsystems-ch
  environment: production

images:
  - name: ghcr.io/rbxrobotica/rbx-ia-br
    newTag: sha-deb37f4
