#!/usr/bin/env bash
# Generates rbac.yml: 8 Roles (corbetti-agent-writer, one per target namespace) +
# 32 RoleBindings (4 agent SAs x 8 namespaces). Output is committed and ArgoCD-synced;
# regenerate on scope change. ADR-0500 Amendment 2026-07 / rbx-security AGENT-KUBE-001.
set -euo pipefail

SAS=(corbetti-claude corbetti-codex corbetti-kimi corbetti-glm)
NSS=(robson rbx-commerce rbx-maestro rbx-comms truthmetal eden llm-gateway rbx-observability)

OUT="$(dirname "$0")/rbac.yml"
{
  echo "# GENERATED by gen-rbac.sh — DO NOT EDIT."
  echo "# 8 Roles (corbetti-agent-writer) + 32 RoleBindings (4 SAs x 8 namespaces)."
  echo "# ADR-0500 Amendment 2026-07 / rbx-security AGENT-KUBE-001."
  echo ""
  for ns in "${NSS[@]}"; do
    cat <<EOF
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: corbetti-agent-writer
  namespace: ${ns}
  labels:
    app.kubernetes.io/name: corbetti-agent-writer
rules:
  # Near-admin WRITE across all apiGroups/kinds in this namespace (locked verb scope).
  # selfHeal+prune reverts applies to ArgoCD-managed kinds; persistent mutation still
  # goes through PR -> review -> ArgoCD. Destructive-on-Secret/PVC and RBAC writes are
  # denied by ValidatingAdmissionPolicy VAP-1 (see platform/agent-access/).
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["create", "update", "patch", "delete", "deletecollection"]
  # Read surface for ops triage (writes audited at Metadata level; reads are not).
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps", "secrets", "services", "endpoints",
                "persistentvolumeclaims", "events", "serviceaccounts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  # exec + port-forward (audited as CREATE/CONNECT).
  - apiGroups: [""]
    resources: ["pods/exec", "pods/portforward"]
    verbs: ["create"]
EOF
    for sa in "${SAS[@]}"; do
      cat <<EOF
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${sa}--${ns}
  namespace: ${ns}
  labels:
    app.kubernetes.io/name: ${sa}--${ns}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: corbetti-agent-writer
subjects:
  - kind: ServiceAccount
    name: ${sa}
    namespace: corbetti-agents
EOF
    done
  done
} > "$OUT"

roles=$(grep -c '^kind: Role$' "$OUT" || true)
bindings=$(grep -c '^kind: RoleBinding$' "$OUT" || true)
echo "Generated $OUT ($roles Roles, $bindings RoleBindings)."
