apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - secretstore.yml
  - external-secrets.yml
  - web.yml
  - session-bff.yml
images:
  - name: ghcr.io/rbxrobotica/rbx-briefing-btc
    newTag: sha-9e2913e
  - name: ghcr.io/rbxrobotica/rbx-session-bff
    newTag: sha-515765f
labels:
  - pairs:
      app.kubernetes.io/part-of: rbx-briefing-btc
      environment: sandbox
    includeSelectors: false
