apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rbx-commerce
resources:
  - namespace.yml
  - rbac-external-secrets.yml
  - secretstore.yml
  - rbx-commerce-secret.yml
  - rbx-commerce-ingress.yml
  - rbx-commerce-deploy.yml
  - rbx-commerce-svc.yml
  - rbx-commerce-web-deploy.yml
  - rbx-commerce-web-svc.yml
images:
  - name: ghcr.io/rbxrobotica/rbx-commerce
    newTag: sha-b8baad2fe56e91750311953a59bffb6f0e94ef90
  - name: ghcr.io/rbxrobotica/rbx-commerce-web
    newTag: sha-b8baad2fe56e91750311953a59bffb6f0e94ef90
