apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rbx-commerce
resources:
  - namespace.yml
  - rbac-external-secrets.yml
  - secretstore.yml
  - rbx-commerce-secret.yml
  - rbx-commerce-ingress.yml
  - rbx-commerce-deploy.yml
  - rbx-commerce-svc.yml
  - rbx-commerce-web-deploy.yml
  - rbx-commerce-web-svc.yml
images:
  - name: ghcr.io/rbxrobotica/rbx-commerce
    newTag: sha-102672dd6f29f0b5e1bb3335819403ce77b7f117
  - name: ghcr.io/rbxrobotica/rbx-commerce-web
    newTag: sha-102672dd6f29f0b5e1bb3335819403ce77b7f117
