apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rbx-commerce

resources:
  - namespace.yml
  - rbac-external-secrets.yml
  - secretstore.yml
  - rbx-commerce-secret.yml
  - rbx-commerce-ingress.yml
  - rbx-commerce-deploy.yml
  - rbx-commerce-svc.yml
  - rbx-commerce-web-deploy.yml
  - rbx-commerce-web-svc.yml

images:
  - name: ghcr.io/rbxrobotica/rbx-commerce
    newTag: sha-30c525c96c904c45824311a9e32f59a4644d56ff
  - name: ghcr.io/rbxrobotica/rbx-commerce-web
    newTag: sha-30c525c96c904c45824311a9e32f59a4644d56ff
