# ServiceAccount and RBAC for External Secrets to read secrets from rbx-ia-br
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-reader
  namespace: rbx-commerce

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-commerce-secret
  namespace: rbx-ia-br
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rbx-commerce-secrets"]
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-reader-commerce
  namespace: rbx-ia-br
subjects:
  - kind: ServiceAccount
    name: external-secrets-reader
    namespace: rbx-commerce
roleRef:
  kind: Role
  name: read-commerce-secret
