# ArgoCD Application: thalamus
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thalamus
  namespace: argocd
  labels:
    app.kubernetes.io/name: thalamus
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: thalamus
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rbx-applications

  source:
    repoURL: https://github.com/rbxrobotica/rbx-infra
    targetRevision: main
    path: apps/prod/thalamus

  destination:
    server: https://kubernetes.default.svc
    namespace: thalamus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
