apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rbx-observability-langfuse
  namespace: rbx-observability
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: kubernetes-store
    kind: SecretStore
  target:
    name: rbx-observability-langfuse
    creationPolicy: Owner
  data:
    - secretKey: LANGFUSE_HOST
      remoteRef:
        key: rbx-observability-langfuse
        property: LANGFUSE_HOST
    - secretKey: LANGFUSE_PUBLIC_KEY
      remoteRef:
        key: rbx-observability-langfuse
        property: LANGFUSE_PUBLIC_KEY
    - secretKey: LANGFUSE_SECRET_KEY
      remoteRef:
        key: rbx-observability-langfuse
        property: LANGFUSE_SECRET_KEY
