apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - secretstore.yml
  - rbac-external-secrets.yml
  - externalsecret-token.yml
  - externalsecret-langfuse.yml
  - deploy.yml
  - svc.yml

images:
  - name: ghcr.io/rbxrobotica/rbx-observability
    newTag: latest
