apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eden-api-ingress
  namespace: eden
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: eden-eden-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.eden.rbx.ia.br
        - api.eden.rbxsystems.ch
      secretName: eden-api-tls
  rules:
    - host: api.eden.rbx.ia.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eden-api
                port:
                  number: 80
    - host: api.eden.rbxsystems.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eden-api
                port:
                  number: 80
