apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - middleware-https.yml
  - secretstore.yml
  - externalsecret-s3.yml
  - externalsecret-maestro-dashboard.yml
  - api-deploy.yml
  - api-svc.yml
  - api-ingress.yml
  - portal-deploy.yml
  - portal-svc.yml
  - portal-ingress.yml

images:
  - name: ghcr.io/rbxrobotica/eden-api
    newTag: sha-a038bc0
  - name: ghcr.io/rbxrobotica/eden-portal
    newTag: sha-a038bc0
