#!/usr/bin/env bash
# init-vault-from-pass.sh
#
# Generates bootstrap/ansible/group_vars/all/vault.yml from pass.
# Run this before ansible-playbook to ensure vault.yml is up-to-date.
#
# Usage:
#   bash bootstrap/scripts/init-vault-from-pass.sh
#
# Requirements:
#   - pass is installed and unlocked
#   - All required pass entries exist (see docs/infra/SECRETS.md for Day-0 setup)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT_FILE="${SCRIPT_DIR}/../ansible/group_vars/all/vault.yml"

echo "==> Reading secrets from pass..."

# Read all required secrets upfront — fail fast if any are missing
ROBSON_DB_PASS="$(pass show rbx/robson/db-password)"
TRUTHMETAL_DB_PASS="$(pass show rbx/truthmetal/db-password)"
ROBSON_TESTNET_DB_PASS="$(pass show rbx/robson-testnet/db-password)"
PDNS_API_KEY="$(pass show rbx/dns/pdns-api-key)"
PDNS_DB_PASS="$(pass show rbx/dns/pdns-db-password)"

echo "==> Writing vault.yml (gitignored)..."

cat > "${VAULT_FILE}" << EOF
# vault.yml — GENERATED by init-vault-from-pass.sh
# DO NOT EDIT MANUALLY. Re-run the script to regenerate.
# This file is gitignored and ephemeral. Source of truth: pass.

# Application database passwords (jaguar)
paradedb_robson_password: "${ROBSON_DB_PASS}"
paradedb_truthmetal_password: "${TRUTHMETAL_DB_PASS}"
paradedb_robson_testnet_password: "${ROBSON_TESTNET_DB_PASS}"

# PowerDNS database password (jaguar — pdns db)
pdns_db_password: "${PDNS_DB_PASS}"

# PowerDNS API key (primary only — local management)
pdns_api_key: "${PDNS_API_KEY}"
EOF

echo "==> vault.yml written to ${VAULT_FILE}"
echo ""
echo "You can now run:"
echo "  ansible-playbook bootstrap/ansible/site.yml -i bootstrap/ansible/inventory/hosts.yml"
