# Kustomization for rbx-ia-br (rbx.ia.br)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - middleware-https.yml
  - deploy.yml
  - svc.yml
  - ingress.yml
  - secretstore-k8s.yml
  - rbac-external-secrets-reader.yml

commonLabels:
  app.kubernetes.io/part-of: rbx-ia-br
  environment: production

images:
  - name: ghcr.io/rbxrobotica/rbx-ia-br
    newTag: sha-b71e8e2
