# SecretStore for reading secrets from Kubernetes API (same cluster)
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-store
  namespace: rbx-ia-br
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: external-secrets-reader
      server:
        url: https://kubernetes.default.svc.cluster.local
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
