apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rbx-console-users-access
  namespace: rbx-console
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: kubernetes-store
    kind: SecretStore
  target:
    name: rbx-console-users-access
    creationPolicy: Owner
  data:
    - secretKey: RBX_IDENTITY_USERS_ACCESS_SERVICE_KEY
      remoteRef:
        key: rbx-console-users-access
        property: RBX_IDENTITY_USERS_ACCESS_SERVICE_KEY
    - secretKey: RBX_COMMERCE_USERS_ACCESS_SERVICE_KEY
      remoteRef:
        key: rbx-commerce-secrets
        property: COMMERCE_SERVICE_KEY
    - secretKey: RBX_COMMERCE_USERS_ACCESS_TENANT_ID
      remoteRef:
        key: rbx-console-users-access
        property: RBX_COMMERCE_USERS_ACCESS_TENANT_ID
