# Kustomization for rbx-console (operational console)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rbx-console
resources:
  - namespace.yml
  - rbac-external-secrets.yml
  - secretstore.yml
  - externalsecret-users-access.yml
  - externalsecret-session-bff.yml
  - session-bff.yml
  - middleware.yml
  - deploy.yml
  - svc.yml
  - certificate.yml
  - ingressroute.yml
commonLabels:
  app.kubernetes.io/part-of: rbx-console
  environment: production
images:
  - name: ghcr.io/rbxrobotica/rbx-console
    newTag: sha-c2338c3
