# ServiceAccount and RBAC for External Secrets to read Users & Access secrets from rbx-ia-br.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-reader
  namespace: rbx-console

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-rbx-console-users-access
  namespace: rbx-ia-br
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - rbx-console-users-access
      - rbx-commerce-secrets
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-reader-console-users-access
  namespace: rbx-ia-br
subjects:
  - kind: ServiceAccount
    name: external-secrets-reader
    namespace: rbx-console
roleRef:
  kind: Role
  name: read-rbx-console-users-access
  apiGroup: rbac.authorization.k8s.io
